# SPDX-FileCopyrightText: 2023-2024 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  disable:
    - containedctx
    - cyclop
    - depguard
    - forbidigo
    - funlen
    - gocyclo
    - godot
    - godox
    - ireturn
    - lll
    - maintidx
    - makezero
    - mnd
    - nestif
    - nlreturn
    - nolintlint
    - paralleltest
    - prealloc
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - testpackage
    - thelper
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gomodguard:
      blocked:
        modules:
          - github.com/pkg/errors:
              recommendations:
                - errors
    misspell:
      locale: US
    tagliatelle:
      case:
        rules:
          json: snake
          xml: snake
          yaml: snake
        use-field-name: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(cunicu.li/skeleton)
        - blank
        - dot
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
