# SPDX-FileCopyrightText: 2024 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

nodeLinker: node-modules
packageExtensions:
  '@docusaurus/theme-mermaid@*':
    peerDependencies:
      '@docusaurus/theme-common': '*'