package gont

import (
	"errors"
	"fmt"
	"strings"
	"syscall"

	"net"
	"os"
	"path/filepath"

	"github.com/vishvananda/netns"
)

type Network struct {
	Name     string
	Nodes    map[string]Node
	HostNode *Host
	BasePath string

	Persistent bool
	NSPrefix   string

	DefaultOptions Options
}

func HostNode(n *Network) *Host {
	baseNs, err := netns.Get()
	if err != nil {
		return nil
	}

	baseHandle, err := netlink.NewHandle()
	if err != nil {
		return nil
	}

	return &Host{
		BaseNode: BaseNode{
			name: "host",
			Namespace: &Namespace{
				Name:     "base",
				NsHandle: baseNs,
				Handle:   baseHandle,
			},
			Network: n,
		},
	}
}

func NewNetwork(name string, opts ...Option) (*Network, error) {
	if name == "" {
		name = GenerateNetworkName()
	}

	basePath := filepath.Join(varDir, name)

	n := &Network{
		Name:           name,
		BasePath:       basePath,
		Nodes:          map[string]Node{},
		DefaultOptions: Options{},
		NSPrefix:       "gont-",
	}

	// Apply network specific options
	for _, opt := range opts {
		if nopt, ok := opt.(NetworkOption); ok {
			nopt.Apply(n)
		}
	}

	if stat, err := os.Stat(basePath); err == nil && stat.IsDir() {
		return nil, syscall.EEXIST
	}

	for _, path := range []string{"files", "nodes"} {
		path = filepath.Join(basePath, path)
		if err := os.MkdirAll(path, 0644); err != nil {
			return nil, err
		}
	}

	n.HostNode = HostNode(n)
	if n.HostNode == nil {
		return nil, errors.New("failed to create host node")
	}

	if err := n.UpdateHostsFile(); err != nil {
		return nil, fmt.Errorf("failed to update hosts file: %w", err)
	}

	return n, nil
}

// Getter

func (n *Network) Hosts() []*Host {
	hosts := []*Host{}

	for _, node := range n.Nodes {
		if host, ok := node.(*Host); ok {
			hosts = append(hosts, host)
		}
	}

	return hosts
}

func (n *Network) Switches() []*Switch {
	switches := []*Switch{}

	for _, node := range n.Nodes {
		if sw, ok := node.(*Switch); ok {
			switches = append(switches, sw)
		}
	}

	return switches
}

func (n *Network) Routers() []*Router {
	routers := []*Router{}

	for _, node := range n.Nodes {
		if router, ok := node.(*Router); ok {
			routers = append(routers, router)
		}
	}

	return routers
}

func (n *Network) Teardown() error {
	for _, node := range n.Nodes {
		if err := node.Teardown(); err != nil {
			return err
		}
	}

	if n.BasePath != "" {
		os.RemoveAll(n.BasePath)
	}

	return nil
}

func (n *Network) Close() error {
	if !n.Persistent {
		if err := n.Teardown(); err != nil {
			return err
		}
	}

	return nil
}

// UpdateHostsFile writes the addresses and hostnames of all nodes
// into a file located at /run/gont/<network>/files/etc/hosts
//
// Processes started via BaseNode.Run or BaseNode.Start, will see
// this file bind mounted at /etc/hosts
func (n *Network) UpdateHostsFile() error {
	fn := filepath.Join(n.BasePath, "files", "etc", "hosts")
	if err := os.MkdirAll(filepath.Dir(fn), 0755); err != nil {
		return err
	}

	f, err := os.OpenFile(fn, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		return err
	}

	fmt.Fprintln(f, "# Autogenerated hosts file by Gont")

	hosts := map[string][]string{}

	IPv4loopback := net.IPv4(127, 0, 0, 1)

	hosts[IPv4loopback.String()] = []string{"localhost", "localhost.localdomain", "localhost4", "localhost4.localdomain4"}
	hosts[net.IPv6loopback.String()] = []string{"localhost", "localhost.localdomain", "localhost6", "localhost6.localdomain6"}

	add := func(name string, ip net.IP) {
		addr := ip.String()
		if hosts[addr] == nil {
			hosts[addr] = []string{}
		}

		found := false
		for _, n := range hosts[addr] {
			if n == name {
				found = true
			}
		}

		if !found {
			hosts[addr] = append(hosts[addr], name)
		}
	}

	for _, node := range n.Nodes {
		if host, ok := node.(*Host); ok {
			for _, i := range host.Interfaces {
				for _, a := range i.Addresses {
					add(host.name, a.IP)
					add(host.name+"-"+i.Name, a.IP)
				}
			}
		}
	}

	for addr, names := range hosts {
		fmt.Fprintf(f, "%s %s\n", addr, strings.Join(names, " "))
	}

	if err := f.Sync(); err != nil {
		return err
	}

	return nil
}
